/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class RoaringBitmap {
  constructor()
  add(value: number): void
  has(value: number): boolean
  remove(value: number): void
  len(): number
  isEmpty(): boolean
  serialize(): Array<number>
  deserialize(bytes: Array<number>): void
}
